const SECONDS_IN_DAY = 60 * 60 * 24;
const SECONDS_IN_MONTH = SECONDS_IN_DAY * 30.42;

const EMISSION_SCHEDULE = [
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch: 1200000 }, // Day     1
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch: 1538462 }, // Day     2
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch: 1077844 }, // Day     3
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  829493 }, // Day     4
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  647157 }, // Day     5
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  567823 }, // Day     6
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  490463 }, // Day     7
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  431655 }, // Day     8
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  385439 }, // Day     9
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  348162 }, // Day    10
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  317460 }, // Day    11
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  291734 }, // Day    12
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  269865 }, // Day    13
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  251046 }, // Day    14
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  234681 }, // Day    15
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  220318 }, // Day    16
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  201612 }, // Day    17
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  196292 }, // Day    18
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  186143 }, // Day    19
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  176991 }, // Day    20
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  168697 }, // Day    21
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  161146 }, // Day    22
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  154242 }, // Day    23
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  147905 }, // Day    24
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  142068 }, // Day    25
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  136674 }, // Day    26
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  131675 }, // Day    27
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  127029 }, // Day    28
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  122699 }, // Day    29
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:  118655 }, // Day    30
    { entryDuration: SECONDS_IN_DAY,   epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   93598 }, // Day    31
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   94350 }, // Month   2
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   84988 }, // Month   3
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   78346 }, // Month   4
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   73193 }, // Month   5
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   68984 }, // Month   6
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   65424 }, // Month   7
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   62314 }, // Month   8
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   59622 }, // Month   9
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   57189 }, // Month  10
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   54988 }, // Month  11
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   52979 }, // Month  12
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   51131 }, // Month  13
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   49420 }, // Month  14
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   47827 }, // Month  15
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   46337 }, // Month  16
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   44937 }, // Month  17
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   43617 }, // Month  18
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   42369 }, // Month  19
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   41184 }, // Month  20
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   40058 }, // Month  21
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   38984 }, // Month  22
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   37957 }, // Month  23
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   36975 }, // Month  24
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   36032 }, // Month  25
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   35126 }, // Month  26
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   34255 }, // Month  27
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   33415 }, // Month  28
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   32605 }, // Month  29
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   31822 }, // Month  30
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   31065 }, // Month  31
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   30332 }, // Month  32
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   29622 }, // Month  33
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   28932 }, // Month  34
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   28263 }, // Month  35
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   27613 }, // Month  36
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   26980 }, // Month  37
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   26364 }, // Month  38
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   25764 }, // Month  39
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   25180 }, // Month  40
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   24610 }, // Month  41
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   24053 }, // Month  42
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   23510 }, // Month  43
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   22979 }, // Month  44
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   22460 }, // Month  45
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   21953 }, // Month  46
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   21456 }, // Month  47
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   20970 }, // Month  48
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   20494 }, // Month  49
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   20028 }, // Month  50
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   19570 }, // Month  51
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   19122 }, // Month  52
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   18682 }, // Month  53
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   18251 }, // Month  54
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   17827 }, // Month  55
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   17411 }, // Month  56
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   17002 }, // Month  57
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   16601 }, // Month  58
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   16206 }, // Month  59
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   15818 }, // Month  60
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   15436 }, // Month  61
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   15061 }, // Month  62
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   14691 }, // Month  63
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   14328 }, // Month  64
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   13970 }, // Month  65
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   13617 }, // Month  66
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   13270 }, // Month  67
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   12928 }, // Month  68
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   12591 }, // Month  69
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   12259 }, // Month  70
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   11931 }, // Month  71
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   11608 }, // Month  72
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   11290 }, // Month  73
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   10976 }, // Month  74
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   10666 }, // Month  75
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   10360 }, // Month  76
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:   10058 }, // Month  77
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    9760 }, // Month  78
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    9466 }, // Month  79
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    9175 }, // Month  80
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    8889 }, // Month  81
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    8605 }, // Month  82
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    8325 }, // Month  83
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    8049 }, // Month  84
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    7776 }, // Month  85
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    7506 }, // Month  86
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    7239 }, // Month  87
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    6975 }, // Month  88
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    6714 }, // Month  89
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    6456 }, // Month  90
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    6201 }, // Month  91
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    5948 }, // Month  92
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    5699 }, // Month  93
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    5452 }, // Month  94
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    5207 }, // Month  95
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    4966 }, // Month  96
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    4726 }, // Month  97
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    4490 }, // Month  98
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    4255 }, // Month  99
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    4023 }, // Month 100
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    3793 }, // Month 101
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    3566 }, // Month 102
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    3341 }, // Month 103
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    3118 }, // Month 104
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    2897 }, // Month 105
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    2678 }, // Month 106
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    2461 }, // Month 107
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    2246 }, // Month 108
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    2033 }, // Month 109
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    1822 }, // Month 110
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    1614 }, // Month 111
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    1406 }, // Month 112
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:    1201 }, // Month 113
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:     998 }, // Month 114
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:     796 }, // Month 115
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:     596 }, // Month 116
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:     398 }, // Month 117
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:     202 }, // Month 118
    { entryDuration: SECONDS_IN_MONTH, epochDuration: SECONDS_IN_DAY, rewardsPerEpoch:       7 }, // Month 119
];

module.exports = EMISSION_SCHEDULE;
